language: node_js
node_js:
  - '6.10'
  - '7.10'
before_install:
  - npm install -g typescript
  - npm install
  - npm install istanbul coveralls
script:
  - tsc
  - npm test
  - npm run travis
branches:
  only:
    - master
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
