language: node_js
node_js:
  - '6.10'
  - '7.10'
before_install:
  - npm install -g typescript
script:
  - "npm run test"
branches:
  only:
    - master
after_success:
  - "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
