core:
  api_url: "https://cactus.exoz.one/api/"
  cereus:
    url: "http://localhost:5023"
    response_endpoint: "response"

redis:
  db: 0
  host: "localhost"
  port: 6379
  password: ""

rabbitmq:
  host: ""
  port: 5743
  username: ""
  password: ""
  queues:
    messages: "messages"
    events: "events"